### PR TITLE
refactor(plugin): add file to consolidate chrome/firefox APIs

### PR DESCRIPTION
**Pull request by abhishek-nigam**
**Describe the PR**
At 2-3 places in the codebase, we're checking if the browser is chrome or firefox, and hen using the corresponding APIs chrome.* or browser.* respectively. To reduce code repetition this adds a file browser-compat.js that exposes objects corresponding to various browser APIs such that they can be used by other functions in a browser agnostic way.

**Steps to test the PR**
We need to test all flows in our browser extension where browser specific APIs are being called

**Expected behavior**
It should work without error

**Additional context**
These changes were done for https://github.com/tattle-made/Uli/issues/325

### CODE REVIEW

**Comment by dennyabrain** [comment]
@abhishek-nigam thank you so much! we had created an issue that was small in scope for hacktoberfest but your approach is better in the long run. We might need some time to test this out thoroughly so bear with us for that but this is a step in good direction.

**Comment by abhishek-nigam** [comment]
Hi @dennyabrain Good morning! Please let me know if any help/change is needed from my side.

**Comment by dennyabrain** [comment]
Hi @abhishek-nigam 
We were working on a [release](https://github.com/tattle-made/Uli/releases/tag/v0.1.14) last week and didn't want to merge your PR since it would have needed more thorough testing. @aatmanvaidya and I would most likely be able to test out your PR this week and merge. Thanks for resolving the merge conflicts. we were anticipating those as well and this reduces our workload. thank you!

**Comment by abhishek-nigam** [comment]
Hi @dennyabrain That's totally understandable. Welcome and thanks for letting me know!

**Comment by aatmanvaidya** [comment]
hi @abhishek-nigam 
I am reviewing your PR, I see some changes have to be made, will it be convenient for you to meet and we can discuss, there are a few changes I feel I can communicate better over a call than text?

**Comment by abhishek-nigam** [comment]
Hi @aatmanvaidya Sure, messaging you on Slack

**Comment by aatmanvaidya** [comment]
Hello @abhishek-nigam , thank you so much for the work, we have merged it!

Now the task ahead is to make the code cross platform in the other sections of the code base using the `browser-compact.js` file that you created. I have listed it down in this issue - https://github.com/tattle-made/Uli/issues/487. I will be taking this issue up

**Pull request merged**
