### PR TITLE
Changes made to code snippet

### PR DESCRIPTION
**Pull request by plon-Susk7**
---
name: Code Snippet Highlight
about: Create a report to help us improve
title: ''
labels: Feature Enhancement
assignees: ''@plon-Susk7

---

**Describe the PR**
Written custom code snippet highlighting code to highlight code snippets on blogs.

**Steps to test the PR**
npm run start on website folder. Then navigate to blog and click on first blog article.

**Expected behavior**
The code snippet is now has a dark background color.

**Screenshots**
image

**Additional context**
Nope

### CODE REVIEW

**Comment by dennyabrain** [comment]
@aatmanvaidya the way this is done, it would require adding a custom react component to our markdown files. I'd prefer if we used the markdown syntax for writing the code blocks. Possible to link here how it was done on our website?

**Comment by plon-Susk7** [comment]
@aatmanvaidya thanks for the feedback. I will work on it tomorrow.

**Comment by plon-Susk7** [comment]
Hi @aatmanvaidya  I made the necessary changes and pushed the code to my branch. Please have a look at it.
Attaching images for your reference:
image

**Comment by dennyabrain** [comment]
lgtm

**Review by aatmanvaidya — APPROVED** [review]

**Comment by aatmanvaidya** [comment]
@dennyabrain looks good to me as well, can be merged!

**Comment by dennyabrain** [comment]
Thank you @plon-Susk7!
If working on frontend or Gatsby is of interest do let us know. We have open issues on those that we can direct you to.

**Pull request merged**
