### PR TITLE
Fix potential DoS

### PR DESCRIPTION
**Pull request by duggalsu**
- Added upload file size limits
- This fixes https://github.com/tattle-made/security/issues/14

### CODE REVIEW

**Comment by dennyabrain** [comment]
Thanks. Will take me some time to test this. Will keep you posted.

**Comment by duggalsu** [comment]
No, I can't test this from my end. You will have to test this.

**Comment by dennyabrain** [comment]
@aatmanvaidya We need to test this code block basically : 
https://github.com/tattle-made/Uli/blob/93eab95d7ed8357de4ccc0c52325cfba7ff703cc/browser-extension/api-server/index.js#L120-L161

its an POST endpoint called `/archive`
This allows us to send an image. This handler also uploads this image to aws S3 and sends an email using aws SES. So this exercise will be helpful for you to get used to those services. Just follow the code in this function to get a working understanding of the services. I will share the credentials you have to use

@duggalsu can you share the cURL command here we came up with here?

**Comment by duggalsu** [comment]
@dennyabrain Here is the curl command
```
$ curl -v -H "Authorization: token <ACTUAL-TOKEN>" -H "Content-Type: multipart/form-data" -F url="anything" -F screenshot="screenshot.png" localhost:3000/archive
```

You can get the `accessToken` by running this  command
```
$ curl GET http://localhost:3000/auth/register
```

**Comment by dennyabrain** [comment]
We learnt that multer multipart upload doesn't play well with curl - https://github.com/expressjs/multer/issues/666
we were able to test using Hoppscotch that the 8mb file limit is indeed respected.

Closing this.

**Pull request merged**
