### PR TITLE
[#544] Added uliStore data structure, `getAllTextNodes()` and `locateSlur()` functions

### PR DESCRIPTION
**Pull request by hardik-pratap-singh**
---
name: uliStore v 1.0.0
about: Data structure preparation for efficient storage of slurs

---

**Describe the PR**
PR is related to the discussion done in following comments
- [Comment 1](https://github.com/tattle-made/Uli/issues/583#issuecomment-2229974905)
- [Comment 2](https://github.com/tattle-made/Uli/issues/583#issuecomment-2230489649)

**Steps to test the PR**
Code is added to `plugin/src/transform-general.js`

**Screenshots**

- image

- image

- image

- image

### CODE REVIEW

**Review by aatmanvaidya — DISMISSED** [review]

**Comment by aatmanvaidya** [comment]
Changes required
1. On Line 80 - let's not define the list of Slur words here, `targetWords` list can be an input of the `locateSlur()` function.
2. On Line 130 - you can remove such commented instances of the calling the functions, 
```js
// getAllTextNodes(body);
```
this file should just contain the functions.
This way there is also no need to define `body` on line 79, you can remove that too
```js
let body = document.querySelector("body");
```
3. On Line 78 - you can initialise `uliStore` inside the `getAllTextNodes()` function, as the requirement of the function was that it takes in a `node` as input and returns `uliStore` in return.

**Comment by aatmanvaidya** [comment]
Hi @hardik-pratap-singh, everything looks good, 

just one small thing, if I understand correctly, `targetWords` should also be an input of `locateSlur(uliStore)` right?

**Comment by hardik-pratap-singh** [comment]
> Hi @hardik-pratap-singh, everything looks good,
> 
> just one small thing, if I understand correctly, `targetWords` should also be an input of `locateSlur(uliStore)` right?

That depends where we are going to use this function, but for now I think it will be better to add it as input.

**Comment by aatmanvaidya** [comment]
no no, if there is no export for now that's fine, 

things are looking good, merging now

**Review by aatmanvaidya — APPROVED** [review]

**Pull request merged**
