### PR TITLE
Update aws and multer

### PR DESCRIPTION
**Pull request by duggalsu**
- Updated AWS SDK for JS
- Updated `multer-s3` package
- Migrated AWS code to use new SDK
- For reviewing an testing code, refer to issue https://github.com/tattle-made/Uli/issues/472

### CODE REVIEW

**Comment by aatmanvaidya** [comment]
Hello @duggalsu , I review the PR, I am getting an error

To review this PR
1. I removed the `node_modules` and then re-installed the packages by doing `npm install`
2. I added the AWS `keys` and `bucket` name to the `env` file. 
3. Then I started the backend server by doing `docker-compose up`
4. Then , I opened `Postman`, in the form-data I added a png file called `screenshot.png`
5. After that when I send a request to `http://localhost:3000/archive`

### I am getting this error
```bash
api-server                  | Error: Region is missing
api-server                  |     at default (/app/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10:15)
api-server                  |     at /app/node_modules/@smithy/node-config-provider/dist-cjs/fromStatic.js:6:83
api-server                  |     at /app/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
api-server                  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api-server                  |     at async coalesceProvider (/app/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
api-server                  |     at async /app/node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:28
api-server                  |     at async region (/app/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:17:36)
api-server                  |     at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:6:32
api-server                  |     at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
api-server                  |     at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

**Comment by duggalsu** [comment]
Hey @aatmanvaidya , since the `aws-sdk` is now modularized and updated with breaking changes, I used `aws-sdk-js-codemod` for automatic migration from v2 to v3. This removed the `AWS.config.update()` and added the `region` directly to `const sendPromise = new SES()` in the `email.js` file. The links you mentioned are for the older `aws-sdk` version. I will also have to troubleshoot this to see how to make this work.

I have also updated the version again (non-breaking changes).

**Comment by aatmanvaidya** [comment]
okay so should I review this PR now?

**Comment by duggalsu** [comment]
The new version update would not resolve this. Either of us will still have to troubleshoot this issue and how to resolve it using the latest AWS SDK

**Comment by dennyabrain** [comment]
folks, did you try setting the region ? try setting the environment variable AWS_REGION to "ap-south-1". so something like `AWS_REGION=ap-south-1` in the env file.

**Comment by aatmanvaidya** [comment]
no will test this out

**Comment by aatmanvaidya** [comment]
@dennyabrain that worked, the region error has gone 
but now I am getting tihs error

```bash
api-server                  | AccessDenied: Access Denied
api-server                  |     at throwDefaultError (/app/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
api-server                  |     at /app/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
api-server                  |     at de_PutObjectCommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5721:12)
api-server                  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api-server                  |     at async /app/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
api-server                  |     at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
api-server                  |     at async /app/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
api-server                  |     at async /app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:63:20
api-server                  |     at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
api-server                  |     at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
```

I might need the access via IAM in AWS
- https://stackoverflow.com/questions/39620873/why-is-my-access-denied-on-s3-using-the-aws-sdk-for-node-js

**Review by dennyabrain — APPROVED** [review]
Thanks @duggalsu and @aatmanvaidya 
I noticed that the IAM permissions on aws were not sufficient for this user to upload files on ogbv-plugin-dev.tattle.co.in. I made the changes and now it works. We're good to merge this.

**Comment by dennyabrain** [comment]
@duggalsu the existing conflicts are related to package and package-lock.json. I think you'll be best to resolve those.

**Review by aatmanvaidya — APPROVED** [review]

**Pull request merged**
