### PR TITLE
feat: Improve UI for Slur Crowdsource Feature

### LINKED ISSUE #409: Improve UI for Slur Crowdsource Feature
### Is your feature request related to a problem? Please describe.

In the latest release of Uli v0.1.14 - https://github.com/tattle-made/Uli/releases/tag/v0.1.14

In the crowdsource feature users can now crowdsource slur's and its relevant metadata using Uli. A user can select and right-click on a word to crowdsource it.

The metadata helps in providing better context to slur words. Metadata that can be crowd sourced for a slur is:
1. Level of Severity
2. Casual
3. Appropriated
4. If Appropriated, is it by community or others?
5. What makes it problematic?
6. Category of Abuse

More details about the feature can be found in this issue - https://github.com/tattle-made/Uli/issues/389

We are displaying the all the data in a box that looks like this

All the current code for this can be found it here - `browser-extension/plugin/src/ui-components/atoms/SlurCard.js`
https://github.com/tattle-made/Uli/blob/main/browser-extension/plugin/src/ui-components/atoms/SlurCard.js

We use the Grommet component library for frontend. - https://v2.grommet.io/

## The task is to change the box to a grommet card component. 

1. I have written some code of the card component in this file - `browser-extension/plugin/src/ui-components/atoms/SlurCardComponent.js`
https://github.com/tattle-made/Uli/blob/main/browser-extension/plugin/src/ui-components/atoms/SlurCardComponent.js

This is the Grommet Card Component - https://v2.grommet.io/card

The task is just to complete the code, you have to make sure that everything is responsive and no text overflows etc. 

If there is any other way to also display all the text/ content in the box, please feel free to suggest us those changes.

### PR DESCRIPTION
**Pull request by Snehil-Shah**
Resolves #409 

---
name: feature
title: 'Improve UI for Slur Crowdsource Feature'
labels: enhancement

---

Made the slur card use the Card component instead of the Box component.
The design is kept the same for now with slight changes in padding. Some design changes can be iterated over. I personally like the current design, it's simple and straightforward

**Steps to test the PR**
I have swapped the component to use the new one in `Slur.jsx`, so you can use it as it is to test the changes

**Expected behavior**
The slur metadata in the slur list should look like the screenshots below.

**Screenshots**

card_dim

card_expand

### CODE REVIEW

**Comment by aatmanvaidya** [comment]
Hi, @Snehil-Shah thank you so much for the work

Had some feedback while reviewing the PR

- In the `SlurCard.js` file, was the custom slur card component that we had written, and to structure the contents inside it, we had used the `Table` components from Grommet ( TableRow, TableCell, TableBody etc). This approach is very verbose as you can see, to get away from this, we wanted to use the Card Component from Grommet, hoping we don't have to add tables and all in it. 
  - Currently, in your code you have added the entire table inside the `CardBody`, can you see if its possible to **not** add the table components and just use the card components to create this. 

Please let me know if I can help clarify things even more!

**Comment by Snehil-Shah** [comment]
@aatmanvaidya Agreed that this approach is too verbose. But the thing is, the `Card` component is just a `Box` with flex: true (according to their documentation) and we have just 3 card sub-components, the header, footer and body. I used the footer for the `Show more` anchor, and the body to show the slur metadata. The problem is, card components don't provide anything else to set the layout inside the CardBody, it's still a box. So, I think we will have to stick to a `Table` or manually lay out `Box` and `Text` components to get a similar result...
Would appreciate some clarification on this...

**Comment by Snehil-Shah** [comment]
@aatmanvaidya Ok, so the `CardBody` component is just a `Box` component with flex: true (acc to their docs). So it doesn't provide ways to layout content inside the body. We have to use a different component for that (like I used a Table previously).

So to get away from the *verbosity*, I used a `DataTable` instead to layout the content and the code is now much cleaner and abstracted and it looks great too:

image

image

We can of course change the things like which column is bolded etc. 

Is it okay now?

**Comment by aatmanvaidya** [comment]
@Snehil-Shah this approach looks neat, give me some time, I will review it and get back to you as soon as possible

**Comment by Snehil-Shah** [comment]
@aatmanvaidya Sure! Also, changed the font from bold to the original one, looks cleaner:

image

image

**Comment by aatmanvaidya** [comment]
Hi @Snehil-Shah, looks great

reviewed and tested out your PR locally

just two changes are required 

1. The footer where you have added the `See More` and `See Less` buttons, can you center them? as they originally were at the center?
2. There is one more feature in Uli, where a user can select a word, right click on it and add the slur to Uli, once the user does this, the slur also gets added to the `Crowdsourced Slur List`. And since the user has only added the slur and not the `metadata`, the UI at this point looks like this


Screenshot from 2024-04-24 18-19-24


In your PR, in this case, the footer still exists, meaning when a user adds a slur by right clicking on it, the footer of (see more and see less buttons) is still there, which should not be there. Can you fix this?

To make sure the right-click on a word and add it to the slur list feature is working in your development setup, you will have make a small change. 
If you are using Chrome, then in your `mainfest.json` file, make `permissions` section, add this `http://localhost:3000/*`, so your permissions should now looks like this
```json
    "permissions": [
        "storage",
        "webRequest",
        "contextMenus",
        "https://ogbv-plugin.tattle.co.in/*",
        "http://localhost:3000/*"
    ],
```

Hope this helps, please feel free to reach out to me for more clarity!

**Comment by Snehil-Shah** [comment]
image

Done (ignore the pixelated screenshot, I am running it on a bad VM's browser)

I also think the warning message inside the card itself (notice the elevation and shadow around the warning) looks good, than just the warning. What do you think?

Also removed the old component. This PR should be now ready to merge...

**Comment by aatmanvaidya** [comment]
Hi @Snehil-Shah , yes the warning message inside the card looks good!

Thank you so much for your work on this, this looks good, I have tested it out locally, its ready to merge!

**Comment by dennyabrain** [comment]
hey @Snehil-Shah I'm hijacking this comment section for a separate discussion. I noticed your project https://github.com/Snehil-Shah/Multimodal-Image-Search-Engine and wanted to point you towards another project of ours called Feluda that has two open projects in the DMP 2024 program that you might interest you. They are pretty much doing what you did in yoru repo but for audio and video. Here are the links - https://github.com/tattle-made/feluda/issues/82, https://github.com/tattle-made/feluda/issues/81

see if they are of interest. 
Thank you again for the work on this PR

**Comment by Snehil-Shah** [comment]
@dennyabrain Hey, thanks for checking out the project! Feluda seems interesting, will do some R&D around it asap..👍

**Pull request merged**
